version: 0.2

phases:
  install:
    commands:
      - set -e
      - echo "Installing prerequisites..."
      - apt-get update -y || true
      - apt-get install -y unzip wget jq || true
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.5.8/terraform_1.5.8_linux_amd64.zip -O /tmp/terraform.zip
      - unzip -o /tmp/terraform.zip -d /usr/local/bin
      - terraform --version

  pre_build:
    commands:
      - echo "Preparing workspace..."
      - cd infra/terraform
      - echo "Terraform working directory: $(pwd)"
      - terraform init -input=false

  build:
    commands:
      - echo "Searching for tfplan produced by the Plan stage..."
      - |
        TFPLAN_PATH=$(find /codebuild/output -type f -name 'tfplan*' -print -quit || true)
        if [ -n "$TFPLAN_PATH" ]; then
          echo "Found tfplan at: $TFPLAN_PATH"
          cp "$TFPLAN_PATH" ./tfplan
        else
          echo "tfplan not found in artifacts."
        fi
      - |
        if [ -f ./tfplan ]; then
          echo "Applying plan (tfplan) ..."
          terraform apply -input=false -auto-approve ./tfplan
        else
          echo "ERROR: tfplan missing — aborting (to avoid accidental apply)."
          exit 1
        fi

post_build:
  commands:
    - echo "Apply phase finished."
