version: 0.2

phases:
  install:
    commands:
      - set -e
      - apt-get update -y || true
      - apt-get install -y unzip wget jq python3-pip || true
      - echo "Installing Terraform..."
      - |
        if wget -q -O "${TF_ZIP}" "${TF_URL}"; then
          echo "Terraform zip downloaded to ${TF_ZIP}"
          unzip -o "${TF_ZIP}" -d /usr/local/bin
        else
          echo "Download failed — falling back to HashiCorp APT repo install"
          wget -q -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg || true
          DIST_CODENAME=$(lsb_release -cs || echo "focal")
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com ${DIST_CODENAME} main" > /etc/apt/sources.list.d/hashicorp.list
          apt-get update -y || true
          apt-get install -y terraform || { echo "apt install terraform failed"; exit 1; }
        fi
      - terraform --version || true
      
  pre_build:
    commands:
      - echo "Preparing terraform workspace"
      - terraform init -input=false
  build:
    commands:
      - echo "Running terraform plan"
      - terraform plan -out=tfplan.binary -input=false
artifacts:
  files:
    - tfplan.binary
  discard-paths: no
