version: 0.2

phases:
  install:
    commands:
      - set -e
      - apt-get update -y || true
      - apt-get install -y unzip wget jq python3-pip || true
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.5.8/terraform_1.5.8_linux_amd64.zip -O /tmp/t.zip
      - unzip -o /tmp/t.zip -d /usr/local/bin
  pre_build:
    commands:
      - echo "Preparing terraform workspace"
      - cd infra/terraform    # adjust this path to your TF working dir
      - terraform init -input=false
  build:
    commands:
      - echo "Running terraform plan"
      - terraform plan -out=tfplan.binary -input=false
artifacts:
  files:
    - tfplan.binary
  discard-paths: no
